### ISSUE TITLE
to stix slect stix field pop up - search doesnt work properly

### ISSUE THREAD

**Issue by aviv1ron1** [IBM/map-my-shifter#3]
In the to stix, when you select the select field pop up that allows you to select a field from the stix terminology, if you search something and close the window, and then open the window again - it is still filtered according to the prior search, although the search text box is empty.
steps to reproduce:
open to stix screen. create an object. click the "select field" button.
enter a search term. the options get filtered by the search term.
either select a field or click the close X button.
click the select field again - the options are still filtered as per the prior search term.
should be - all options show up.

**Comment by barvhaim** [comment]
fixed & deployed to demo, clear cache if you don't see the updated version
